name: SimpleClans
main: net.sacredlabyrinth.phaed.simpleclans.SimpleClans
version: ${project.version}
softdepend: [VanishNoPacket, Permissions, PermissionsBukkit, Vault, PermissionsEx, mChat, mChatSuite]
permissions:
  simpleclans.admin.permissions:
    description: Can grant clans permissions
  simpleclans.admin.reload:
    description: Can reload configuration
  simpleclans.admin.all-seeing-eye:
    description: Can see all clan chats
  simpleclans.admin.resetkdr:
    description: Can reset player kdr (of all or just one)
  simpleclans.mod.verify:
    description: Can verify simpleclans
  simpleclans.mod.ban:
    description: Can ban players from the entire plugin
  simpleclans.mod.disband:
    description: Can disband any clan
  simpleclans.mod.globalff:
    description: Can turn off global friendly fire protection
  simpleclans.mod.nohide:
    description: Messages from these players cannot be hidden via chat commands
  simpleclans.mod.home:
    description: Can set other clan's home
  simpleclans.mod.hometp:
    description: Can teleport to all clans homes
  simpleclans.mod.bypass:
    description: Can bypass restrictions
  simpleclans.mod.nopvpinwar:
    description: Can bypass pvp in wars
  simpleclans.anyone.list:
    description: Can list simpleclans
  simpleclans.anyone.profile:
    description: Can view a clan's profile
  simpleclans.anyone.roster:
    description: Can veiw a clan's member list
  simpleclans.anyone.lookup:
    description: Can lookup a player's info
  simpleclans.anyone.leaderboard:
    description: Can view the leaderboard
  simpleclans.anyone.alliances:
    description: Can view alliances by clan
  simpleclans.anyone.rivalries:
    description: Can view rivalries by clan
  simpleclans.member.profile:
    description: Can view his own clan's profile
  simpleclans.member.roster:
    description: Can view his own clan's member list
  simpleclans.member.lookup:
    description: Can view his own player info
  simpleclans.member.vitals:
    description: Can view his clan's vitals
  simpleclans.member.coords:
    description: Can view his clan's coords
  simpleclans.member.stats:
    description: Can view his simpleclans stats
  simpleclans.member.bb:
    description: Can view his clan's bulletin board
  simpleclans.member.bb-add:
    description: Can add to his clan's bulletin board
  simpleclans.member.bb-toggle:
    description: Can toggle bb on/off
  simpleclans.member.ff:
    description: Can toggle his own friendly fire
  simpleclans.member.resign:
    description: Can resign from his clan
  simpleclans.member.ally:
    description: Can use ally chat
  simpleclans.member.chat:
    description: Can use clan chat
  simpleclans.member.can-join:
    description: Can join clans
  simpleclans.member.home:
    description: Can tp to home base
  simpleclans.member.resetkdr:
    description: Can reset his kdr
  simpleclans.leader.create:
    description: Can create simpleclans
  simpleclans.leader.verify:
    description: Can verify his clan
  simpleclans.leader.home-set:
    description: Can set home base
  simpleclans.leader.home-regroup:
    description: Can tp entire clan to homebase
  simpleclans.leader.ally:
    description: Can ally his clan with other simpleclans
  simpleclans.leader.rival:
    description: Can start a rivalry with another clan
  simpleclans.leader.modtag:
    description: Can modify his clan's tag
  simpleclans.leader.cape:
    description: Can set his clan's cape url
  simpleclans.member.cape-toggle:
    description: Can toggle his cape on/off
  simpleclans.member.kills:
    description: Can view his and other's kills
  simpleclans.member.tag-toggle:
    description: Can hide his own clan tag
  simpleclans.mod.mostkilled:
    description: Can view his and other's clans mostkilled
  simpleclans.mod.keep-items:
    description: Can keep items when teleporting home
  simpleclans.mod.place:
    description: Can manually place players in clans
  simpleclans.leader.invite:
    description: Can invite players into his clan
  simpleclans.leader.kick:
    description: Can kick players form his tea,
  simpleclans.leader.promote:
    description: Can promote players to clan leaders
  simpleclans.leader.promotable:
    description: Can be promoted to clan leader
  simpleclans.leader.demote:
    description: Can demote clan leaders to normal players
  simpleclans.leader.ff:
    description: Can toggle his clan's friendly fire
  simpleclans.leader.disband:
    description: Can disband his own clan
  simpleclans.leader.settrust:
    description: Can set trust levels for members
  simpleclans.leader.war:
    description: Can start wars
  simpleclans.leader.setrank:
    description: Can set ranks
  simpleclans.leader.coloredtag:
    description: Can use color codes in tags
  simpleclans.member.bank:
    description: Can use banks
  simpleclans.admin.*:
    description: Permissions for admins
    default: op
    children:
      simpleclans.admin.reload: true
      simpleclans.admin.all-seeing-eye: true
      simpleclans.admin.resetkdr: true
  simpleclans.mod.*:
    description: Permissions for moderators
    default: op
    children:
      simpleclans.mod.verify: true
      simpleclans.mod.ban: true
      simpleclans.mod.disband: true
      simpleclans.mod.globalff: true
      simpleclans.mod.bypass: true
      simpleclans.mod.home: true
      simpleclans.mod.mostkilled: true
      simpleclans.mod.keep-items: true
      simpleclans.mod.nopvpinwar: true
      simpleclans.mod.place: true
  simpleclans.anyone.*:
    description: Permissions for anyone
    default: false
    children:
      simpleclans.anyone.list: true
      simpleclans.anyone.profile: true
      simpleclans.anyone.roster: true
      simpleclans.anyone.lookup: true
      simpleclans.anyone.leaderboard: true
      simpleclans.anyone.alliances: true
      simpleclans.anyone.rivalries: true
  simpleclans.member.*:
    description: Permissions for those who can be clan members
    default: false
    children:
      simpleclans.member.can-join: true
      simpleclans.member.profile: true
      simpleclans.member.roster: true
      simpleclans.member.lookup: true
      simpleclans.member.vitals: true
      simpleclans.member.coords: true
      simpleclans.member.stats: true
      simpleclans.member.bb: true
      simpleclans.member.bb-add: true
      simpleclans.member.bb-toggle: true
      simpleclans.member.cape-toggle: true
      simpleclans.member.tag-toggle: true
      simpleclans.member.ff: true
      simpleclans.member.resign: true
      simpleclans.member.ally: true
      simpleclans.member.chat: true
      simpleclans.member.home: true
      simpleclans.member.kills: true
      simpleclans.member.bank: true
      simpleclans.member.resetkdr: true
  simpleclans.leader.*:
    description: Permissions for those who can be clan leaders
    default: false
    children:
      simpleclans.leader.create: true
      simpleclans.leader.verify: true
      simpleclans.leader.ally: true
      simpleclans.leader.rival: true
      simpleclans.leader.modtag: true
      simpleclans.leader.cape: true
      simpleclans.leader.invite: true
      simpleclans.leader.kick: true
      simpleclans.leader.promote: true
      simpleclans.leader.promotable: true
      simpleclans.leader.demote: true
      simpleclans.leader.ff: true
      simpleclans.leader.disband: true
      simpleclans.leader.settrust: true
      simpleclans.leader.war: true
      simpleclans.leader.home-set: true
      simpleclans.leader.home-regroup: true
      simpleclans.leader.setrank: true
      simpleclans.leader.coloredtag: true
